import * as img from '../assets/cards-img';
import * as audio from '../assets/cards-audio';

export const cards = {
  categories: [
    {
      name: 'Action (set A)',
      image: img.dance,
      url: '/action-a',
    },
    {
      name: 'Action (set B)',
      image: img.swim,
      url: '/action-b',
    },
    {
      name: 'Outdoors',
      image: img.outdoors,
      url: '/outdoors',
    },
    {
      name: 'House',
      image: img.house,
      url: '/house',
    },
    {
      name: 'Animal (set A)',
      image: img.cat,
      url: '/animal-a',
    },
    {
      name: 'Animal (set B)',
      image: img.bird,
      url: '/animal-b',
    },
    {
      name: 'Clothes',
      image: img.blouse,
      url: '/clothes',
    },
    {
      name: 'Emotion',
      image: img.smile,
      url: '/emotion',
    },
  ],
  'Action (set A)': [
    {
      name: 'cry',
      translation: 'плакать',
      image: img.cry,
      audioSrc: audio.cry,
    },
    {
      name: 'dance',
      translation: 'танцевать',
      image: img.dance,
      audioSrc: audio.dance,
    },
    {
      name: 'dive',
      translation: 'нырять',
      image: img.dive,
      audioSrc: audio.dive,
    },
    {
      name: 'draw',
      translation: 'рисовать',
      image: img.draw,
      audioSrc: audio.draw,
    },
    {
      name: 'fishing',
      translation: 'ловить рыбу',
      image: img.fish,
      audioSrc: audio.fishing,
    },
    {
      name: 'fly',
      translation: 'летать',
      image: img.fly,
      audioSrc: audio.fly,
    },
    {
      name: 'hug',
      translation: 'обнимать',
      image: img.hug,
      audioSrc: audio.hug,
    },
    {
      name: 'jump',
      translation: 'прыгать',
      image: img.jump,
      audioSrc: audio.jump,
    },
  ],
  'Action (set B)': [
    {
      name: 'open',
      translation: 'открывать',
      image: img.open,
      audioSrc: audio.open1,
    },
    {
      name: 'play',
      translation: 'играть',
      image: img.play,
      audioSrc: audio.play,
    },
    {
      name: 'point',
      translation: 'указывать',
      image: img.point,
      audioSrc: audio.point,
    },
    {
      name: 'ride',
      translation: 'ездить',
      image: img.ride,
      audioSrc: audio.ride,
    },
    {
      name: 'run',
      translation: 'бегать',
      image: img.run,
      audioSrc: audio.run,
    },
    {
      name: 'sing',
      translation: 'петь',
      image: img.sing,
      audioSrc: audio.sing,
    },
    {
      name: 'skip',
      translation: 'прыгать',
      image: img.skip,
      audioSrc: audio.skip,
    },
    {
      name: 'swim',
      translation: 'плавать',
      image: img.swim,
      audioSrc: audio.swim,
    },
  ],
  Outdoors: [
    {
      name: 'sidewalk',
      translation: 'тротуар',
      image: img.sidewalk,
      audioSrc: audio.sidewalk,
    },
    {
      name: 'road',
      translation: 'дорога',
      image: img.road,
      audioSrc: audio.road,
    },
    {
      name: 'tree',
      translation: 'дерево',
      image: img.tree,
      audioSrc: audio.tree,
    },
    {
      name: 'grass',
      translation: 'трава',
      image: img.grass,
      audioSrc: audio.grass,
    },
    {
      name: 'river',
      translation: 'река',
      image: img.river,
      audioSrc: audio.river,
    },
    {
      name: 'bus',
      translation: 'автобус',
      image: img.bus,
      audioSrc: audio.bus,
    },
    {
      name: 'train',
      translation: 'поезд',
      image: img.train,
      audioSrc: audio.train,
    },
    {
      name: 'sun',
      translation: 'солнце',
      image: img.sun,
      audioSrc: audio.sun,
    },
  ],
  House: [
    {
      name: 'table',
      translation: 'стол',
      image: img.table,
      audioSrc: audio.table,
    },
    {
      name: 'lamp',
      translation: 'лампа',
      image: img.lamp,
      audioSrc: audio.lamp,
    },
    {
      name: 'door',
      translation: 'дверь',
      image: img.door,
      audioSrc: audio.door,
    },
    {
      name: 'cupboard',
      translation: 'шкаф',
      image: img.cupboard,
      audioSrc: audio.cupboard,
    },
    {
      name: 'fridge',
      translation: 'холодильник',
      image: img.fridge,
      audioSrc: audio.fridge,
    },
    {
      name: 'window',
      translation: 'окно',
      image: img.window,
      audioSrc: audio.window,
    },
    {
      name: 'armchair',
      translation: 'кресло',
      image: img.armchair,
      audioSrc: audio.armchair,
    },
    {
      name: 'television',
      translation: 'телевизор',
      image: img.television,
      audioSrc: audio.television,
    },
  ],
  'Animal (set A)': [
    {
      name: 'cat',
      translation: 'кот',
      image: img.cat,
      audioSrc: audio.cat,
    },
    {
      name: 'chick',
      translation: 'цыплёнок',
      image: img.chick,
      audioSrc: audio.chick,
    },
    {
      name: 'chicken',
      translation: 'курица',
      image: img.chicken,
      audioSrc: audio.chicken,
    },
    {
      name: 'dog',
      translation: 'собака',
      image: img.dog,
      audioSrc: audio.dog,
    },
    {
      name: 'horse',
      translation: 'лошадь',
      image: img.horse,
      audioSrc: audio.horse,
    },
    {
      name: 'pig',
      translation: 'свинья',
      image: img.pig,
      audioSrc: audio.pig,
    },
    {
      name: 'rabbit',
      translation: 'кролик',
      image: img.rabbit,
      audioSrc: audio.rabbit,
    },
    {
      name: 'sheep',
      translation: 'овца',
      image: img.sheep,
      audioSrc: audio.sheep,
    },
  ],
  'Animal (set B)': [
    {
      name: 'bird',
      translation: 'птица',
      image: img.bird,
      audioSrc: audio.bird,
    },
    {
      name: 'fish',
      translation: 'рыба',
      image: img.fish1,
      audioSrc: audio.fish,
    },
    {
      name: 'frog',
      translation: 'жаба',
      image: img.frog,
      audioSrc: audio.frog,
    },
    {
      name: 'giraffe',
      translation: 'жираф',
      image: img.giraffe,
      audioSrc: audio.giraffe,
    },
    {
      name: 'lion',
      translation: 'лев',
      image: img.lion,
      audioSrc: audio.lion,
    },
    {
      name: 'mouse',
      translation: 'мышь',
      image: img.mouse,
      audioSrc: audio.mouse,
    },
    {
      name: 'turtle',
      translation: 'черепаха',
      image: img.turtle,
      audioSrc: audio.turtle,
    },
    {
      name: 'dolphin',
      translation: 'дельфин',
      image: img.dolphin,
      audioSrc: audio.dolphin,
    },
  ],
  Clothes: [
    {
      name: 'skirt',
      translation: 'юбка',
      image: img.skirt,
      audioSrc: audio.skirt,
    },
    {
      name: 'pants',
      translation: 'брюки',
      image: img.pants,
      audioSrc: audio.pants,
    },
    {
      name: 'blouse',
      translation: 'блузка',
      image: img.blouse,
      audioSrc: audio.blouse,
    },
    {
      name: 'dress',
      translation: 'платье',
      image: img.dress,
      audioSrc: audio.dress,
    },
    {
      name: 'boot',
      translation: 'ботинок',
      image: img.boot,
      audioSrc: audio.boot,
    },
    {
      name: 'shirt',
      translation: 'рубашка',
      image: img.shirt,
      audioSrc: audio.shirt,
    },
    {
      name: 'coat',
      translation: 'пальто',
      image: img.coat,
      audioSrc: audio.coat,
    },
    {
      name: 'shoe',
      translation: 'туфли',
      image: img.shoe,
      audioSrc: audio.shoe,
    },
  ],
  Emotion: [
    {
      name: 'sad',
      translation: 'грустный',
      image: img.sad,
      audioSrc: audio.sad,
    },
    {
      name: 'angry',
      translation: 'сердитый',
      image: img.angry,
      audioSrc: audio.angry,
    },
    {
      name: 'happy',
      translation: 'счастливый',
      image: img.happy,
      audioSrc: audio.happy,
    },
    {
      name: 'tired',
      translation: 'уставший',
      image: img.tired,
      audioSrc: audio.tired,
    },
    {
      name: 'surprised',
      translation: 'удивлённый',
      image: img.surprised,
      audioSrc: audio.surprised,
    },
    {
      name: 'scared',
      translation: 'испуганный',
      image: img.scared,
      audioSrc: audio.scared,
    },
    {
      name: 'smile',
      translation: 'улыбка',
      image: img.smile,
      audioSrc: audio.smile,
    },
    {
      name: 'laugh',
      translation: 'смех',
      image: img.laugh,
      audioSrc: audio.laugh,
    },
  ],
};

export default cards;
